name: Pract_seven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка зависимостей и Qt6
      - name: Install dependencies and Qt6
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip build-essential perl coreutils
          pip3 install aqtinstall
          
      # Список доступных модулей Qt
      - name: List available Qt modules
        run: |
          aqt list-qt linux desktop --modules 6.6.0 gcc_64

      # Установка Qt6.6.0
      - name: Install Qt6
        run: |
          aqt install-qt linux desktop 6.6.0 gcc_64 -O /opt/qt -m qtbase qtsql qttools qtwebengine
          echo "/opt/qt/6.6.0/gcc_64/lib" | sudo tee /etc/ld.so.conf.d/qt6.conf
          sudo ldconfig
          echo "export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH" >> $GITHUB_ENV

      # Проверка установки Qt6
      - name: Check Qt6 installation
        run: |
          ls /opt/qt/6.6.0/gcc_64/bin

      # Установка cppcheck для проверки кода
      - name: Install cppcheck
        run: |
          sudo apt-get install -y cppcheck

      # Сборка проекта с использованием системы сборки qmake
      - name: Build project
        run: |
          export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH
          qmake -project
          qmake
          make

      # Проверка кода с помощью cppcheck
      - name: Run cppcheck
        run: |
          export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH
          cppcheck --enable=all --suppress=missingIncludeSystem .
