name: Pract_seven #Название

on: #указание в каких случаях выполнять
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: #полное указание того, что надо делать
  build:
    runs-on: ubuntu-latest #образ

    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка Qt6 и необходимых модулей
      - name: Install Qt6
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install aqtinstall
          # Устанавливаем последнюю версию Qt6
          aqt install-qt linux desktop latest gcc_64 -O /opt/qt -m qtbase qtsql qttools qtcharts qtwebengine
          echo "/opt/qt/latest/gcc_64/lib" | sudo tee /etc/ld.so.conf.d/qt6.conf
          sudo ldconfig
          echo "export PATH=/opt/qt/latest/gcc_64/bin:$PATH" >> $GITHUB_ENV
      - name: Check Qt6 installation
        run: |
          ls /opt/qt/latest/gcc_64/bin

      # Установка cppcheck для проверки кода
      - name: Install cppcheck
        run: |
          sudo apt-get install -y cppcheck

      # Сборка проекта с использованием системы сборки qmake
      - name: Build project
        run: |
          export PATH=/opt/qt/latest/gcc_64/bin:$PATH
          qmake -project
          qmake
          make

      # Проверка кода с помощью cppcheck
      - name: Run cppcheck
        run: |
          export PATH=/opt/qt/latest/gcc_64/bin:$PATH
          cppcheck --enable=all --suppress=missingIncludeSystem .
