name: Pract_seven #Название

on: #указание в каких случаях выполнять
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: #полное указание того, что надо делать
  build:
    runs-on: fedora-latest #образ

    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List available Qt modules
        run: |
          pip3 install aqtinstall
          aqt list-qt linux desktop --modules 6.6.0 gcc_64


      # Установка зависимостей и Qt6
      - name: Install Qt6
        run: |
            sudo dnf update -y
            sudo dnf install -y python3-pip gcc gcc-c++ make perl coreutils
            pip3 install aqtinstall
            # Установка Qt6.6.0 с доступными модулями
            aqt install-qt linux desktop 6.6.0 gcc_64 -O /opt/qt -m qtbase qttools
            echo "/opt/qt/6.6.0/gcc_64/lib" | sudo tee /etc/ld.so.conf.d/qt6.conf
            sudo ldconfig
            echo "export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH" >> $GITHUB_ENV


      # Проверка установки Qt6
      - name: Check Qt6 installation
        run: |
          ls /opt/qt/6.6.0/gcc_64/bin

      # Установка cppcheck для проверки кода
      - name: Install cppcheck
        run: |
          sudo dnf install -y cppcheck

      # Сборка проекта с использованием системы сборки qmake
      - name: Build project
        run: |
          export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH
          qmake -project
          qmake
          make

      # Проверка кода с помощью cppcheck
      - name: Run cppcheck
        run: |
          export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH
          cppcheck --enable=all --suppress=missingIncludeSystem .
