name: Pract_seven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Установка зависимостей и Qt6
      - name: Install dependencies and Qt6
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python3-pip build-essential perl coreutils
          pip3 install aqtinstall
          
      # Список доступных Qt модулей
      - name: List available Qt modules
        run: |
          aqt list-qt linux desktop --modules 6.6.0 gcc_64

      # Установка всех доступных модулей Qt6
      - name: Install all available Qt6 modules
        run: |
          aqt install-qt linux desktop 6.6.0 gcc_64 -O /opt/qt -m debug_info qt3d qt5compat qtcharts qtconnectivity qtdatavis3d qtgraphs qtgrpc qthttpserver qtimageformats qtlanguageserver qtlocation qtlottie qtmultimedia qtnetworkauth qtpdf qtpositioning qtquick3d qtquick3dphysics qtquickeffectmaker qtquicktimeline qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtshadertools qtspeech qtvirtualkeyboard qtwaylandcompositor qtwebchannel qtwebengine qtwebsockets qtwebview
          echo "/opt/qt/6.6.0/gcc_64/lib" | sudo tee /etc/ld.so.conf.d/qt6.conf
          sudo ldconfig
          echo "export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH" >> $GITHUB_ENV

      # Проверка установки Qt6
      - name: Check Qt6 installation
        run: |
          ls /opt/qt/6.6.0/gcc_64/bin

      # Установка cppcheck для проверки кода
      - name: Install cppcheck
        run: |
          sudo apt-get install -y cppcheck

      # Сборка проекта с использованием системы сборки qmake
      - name: Build project
        run: |
          export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH
          qmake -project
          qmake
          make

      # Проверка кода с помощью cppcheck
      - name: Run cppcheck
        run: |
          export PATH=/opt/qt/6.6.0/gcc_64/bin:$PATH
          cppcheck --enable=all --suppress=missingIncludeSystem .
